services:
  test:
    build:
      context: .
      target: test
    volumes:
      - ./app:/usr/llm/app
      - ./hf_cache:/usr/llm/.cache
  server:
    build:
      context: .
      target: server
    ports:
      - 65432:65432
    volumes:
      - ./app:/usr/llm/app
      - ./hf_cache:/usr/llm/.cache
    environment:
      HF_HOME: /usr/llm/.cache

  client:
    build:
      context: .
      target: rust-client
